name: revalidate-data
on:
  schedule:
    - cron: '0/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call the revalidate api route
        run: |
          curl 'https://shop4ua.com/api/businesses/revalidate?secret=${{ secrets.REVALIDATION_KEY }}'
